// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhjbqR8fQrJbpKD99ObFUTqG5uC1N2cfY',
    appId: '1:323715532903:web:8b71986013e2a963446cc2',
    messagingSenderId: '323715532903',
    projectId: 'mind-library-app',
    authDomain: 'mind-library-app.firebaseapp.com',
    storageBucket: 'mind-library-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCISd_IZ-4LcOLjB4ybTPD1AAZth9hGjpY',
    appId: '1:323715532903:android:7418cc24bf27cdff446cc2',
    messagingSenderId: '323715532903',
    projectId: 'mind-library-app',
    storageBucket: 'mind-library-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBd9CukmT_HM8Oy4NWkgFF1A0FvwO44qk',
    appId: '1:323715532903:ios:6fb853be71450ea7446cc2',
    messagingSenderId: '323715532903',
    projectId: 'mind-library-app',
    storageBucket: 'mind-library-app.firebasestorage.app',
    iosBundleId: 'com.example.mindLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBd9CukmT_HM8Oy4NWkgFF1A0FvwO44qk',
    appId: '1:323715532903:ios:6fb853be71450ea7446cc2',
    messagingSenderId: '323715532903',
    projectId: 'mind-library-app',
    storageBucket: 'mind-library-app.firebasestorage.app',
    iosBundleId: 'com.example.mindLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhjbqR8fQrJbpKD99ObFUTqG5uC1N2cfY',
    appId: '1:323715532903:web:eb967d65312c47ff446cc2',
    messagingSenderId: '323715532903',
    projectId: 'mind-library-app',
    authDomain: 'mind-library-app.firebaseapp.com',
    storageBucket: 'mind-library-app.firebasestorage.app',
  );
}
